### ISSUE TITLE
migration error with whoosh

### ISSUE THREAD

**Issue by revant** [revant/erpnext_feature_board#24]
```
Migrating board.castlecraft.co.in
Updating DocTypes for frappe        : [========================================] 100%
Updating DocTypes for erpnext_feature_board: [========================================] 100%
Updating Dashboard for frappe
Updating Dashboard for erpnext_feature_board
Building search index for board.castlecraft.co.in
Retrieving Routes                   : [==                                      ] 5%
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/migrate.py", line 51, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/migrate.py", line 44, in main
    migrate_sites()
  File "/home/frappe/frappe-bench/commands/migrate.py", line 35, in migrate_sites
    migrate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 95, in migrate
    build_index_for_all_routes()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/search/website_search.py", line 128, in build_index_for_all_routes
    return ws.build()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/search/full_text_search.py", line 37, in build
    self.build_index()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/search/full_text_search.py", line 96, in build_index
    writer = ix.writer()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/whoosh/index.py", line 464, in writer
    return SegmentWriter(self, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/whoosh/writing.py", line 515, in __init__
    raise LockError
whoosh.index.LockError
```

Seems to be during migration from containers.

**Comment by revant** [comment]
Somehow the error doesn't show up with recent upgrades
